#!/usr/bin/env bash
#
# Re-apply our Android customizations after `tauri android init` (which regenerates
# the gen/android project on every build). Run automatically by the Makefile / CI.
#
# Everything we inject lives below as plain, readable text — edit it by hand if you
# need to. It's idempotent: each build reproduces the same result.
#
# NOTE: the `zenithar://` deep-link <intent-filter> is NOT here — Tauri generates it
# itself from `plugins.deep-link.mobile` in tauri.conf.json. Nothing to patch.
#
set -e
GEN="${1:-src-tauri/gen/android}"

# --- Manifest: microphone permission for WebRTC voice calls ------------------
# getUserMedia(audio) needs RECORD_AUDIO declared in the manifest; wry's
# WebChromeClient.onPermissionRequest then prompts for it at runtime and grants the
# webview. (The zenithar:// <intent-filter> is generated by Tauri from
# plugins.deep-link.mobile — not patched here.)
MF="$GEN/app/src/main/AndroidManifest.xml"
grep -q 'RECORD_AUDIO' "$MF" || perl -0pi -e 's{(<uses-permission android:name="android.permission.INTERNET"\s*/>)}{$1\n    <uses-permission android:name="android.permission.RECORD_AUDIO"/>\n    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>}' "$MF"

# --- MainActivity ------------------------------------------------------------
# We overwrite the generated MainActivity with our own: it persists the session
# cookie to SharedPreferences (save on onStop, restore on onCreate) so reopening
# the app stays logged in even if the WebView drops the cookie on a kill.
#
# Edit the Kotlin below freely. The package line is taken from the generated file
# so it follows tauri.conf's `identifier`.

MAIN_ACTIVITY="$(find "$GEN" -name MainActivity.kt -not -path '*/generated/*' | head -1)"
[ -n "$MAIN_ACTIVITY" ] || { echo "✗ MainActivity.kt not found under $GEN"; exit 1; }

PKG="$(grep -m1 '^package ' "$MAIN_ACTIVITY" | awk '{print $2}')"

cat > "$MAIN_ACTIVITY" <<'KOTLIN'
package __PKG__

import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.webkit.CookieManager
import androidx.activity.enableEdgeToEdge
import androidx.core.app.ActivityCompat
import androidx.core.content.ContextCompat

// Login persistence via SharedPreferences (Android settings — no files): we keep
// the current host and its session cookie, save it when the app leaves the
// foreground, and restore it on a plain relaunch so you stay logged in (some
// WebViews drop the cookie when the process is killed).
class MainActivity : TauriActivity() {
  private fun prefs() = getSharedPreferences("zenithar", MODE_PRIVATE)

  override fun onCreate(savedInstanceState: Bundle?) {
    enableEdgeToEdge()
    super.onCreate(savedInstanceState)
    // A deep link logs us into a host. If it differs from last time, first
    // unregister our push token from the OLD server (while its host+cookie are
    // still in prefs) so it stops notifying us, then switch — clearing the stale
    // cookie. The fresh login on the new host re-registers on the next onStop.
    hostFromDeepLink(intent)?.let { newHost ->
      val p = prefs()
      val oldHost = p.getString("host", null)
      if (oldHost != null && oldHost != newHost) {
        val oldCookie = p.getString("cookie", null)
        val token = p.getString("fcm_token", null)
        if (oldCookie != null && token != null) PushReg.unregister(oldHost, oldCookie, token)
      }
      if (oldHost != newHost) p.edit().putString("host", newHost).remove("cookie").apply()
    }
    // Plain relaunch → restore the saved cookie before the host loads. A deep link
    // brings its own fresh login, so skip restore there.
    if (intent?.action != Intent.ACTION_VIEW) restoreCookie()
    askNotifications()
  }

  override fun onStop() {
    super.onStop()
    saveCookie()
    // We have a fresh cookie now — (re)register our push token so messages that
    // arrive while we're backgrounded reach us. No-op until FCM has a token.
    PushReg.register(this)
  }

  // Android 13+ needs runtime consent to show notifications. Declared in the
  // manifest only when FCM is wired, so this is a silent no-op otherwise.
  private fun askNotifications() {
    if (Build.VERSION.SDK_INT >= 33 &&
        ContextCompat.checkSelfPermission(this, Manifest.permission.POST_NOTIFICATIONS)
          != PackageManager.PERMISSION_GRANTED) {
      ActivityCompat.requestPermissions(this, arrayOf(Manifest.permission.POST_NOTIFICATIONS), 1001)
    }
  }

  // zenithar://login?u=<encoded https://host/i/token>  ->  "https://host"
  private fun hostFromDeepLink(i: Intent?): String? {
    if (i?.action != Intent.ACTION_VIEW) return null
    val u = i.data?.getQueryParameter("u") ?: return null
    return try {
      Uri.parse(u).let { if (it.scheme != null && it.host != null) "${it.scheme}://${it.host}" else null }
    } catch (e: Exception) {
      null
    }
  }

  private fun restoreCookie() {
    try {
      val host = prefs().getString("host", null) ?: return
      val cookies = prefs().getString("cookie", null) ?: return
      val cm = CookieManager.getInstance()
      cm.setAcceptCookie(true)
      for (pair in cookies.split("; ")) if (pair.isNotBlank()) cm.setCookie(host, pair)
      cm.flush()
    } catch (e: Exception) {
    }
  }

  private fun saveCookie() {
    try {
      val host = prefs().getString("host", null) ?: return
      val cookies = CookieManager.getInstance().getCookie(host) ?: return
      prefs().edit().putString("cookie", cookies).apply()
    } catch (e: Exception) {
    }
  }
}
KOTLIN
perl -pi -e "s/__PKG__/$PKG/" "$MAIN_ACTIVITY"

echo "→ android: MainActivity patched (cookie persistence via SharedPreferences)"

# --- PushReg: send our FCM token to the backend ------------------------------
# Firebase-FREE on purpose (plain HttpURLConnection), so MainActivity can call it
# whether or not FCM is wired. Reads host+cookie (saved by MainActivity) and the
# token (saved by the messaging service); posts to /api/push/register. No-ops
# until all three exist.
APP_PKG_DIR="$(dirname "$MAIN_ACTIVITY")"
cat > "$APP_PKG_DIR/PushReg.kt" <<'KOTLIN'
package __PKG__

import android.content.Context
import java.net.HttpURLConnection
import java.net.URL

object PushReg {
  // Register this device's token with the server currently in prefs (`host`).
  fun register(ctx: Context) {
    val p = ctx.getSharedPreferences("zenithar", Context.MODE_PRIVATE)
    val host = p.getString("host", null) ?: return
    val cookie = p.getString("cookie", null) ?: return
    val token = p.getString("fcm_token", null) ?: return
    post("$host/api/push/register", cookie, token)
  }

  // Drop this device's token from a SPECIFIC server. Args are explicit (not read
  // from prefs) so a host switch can unregister the OLD server even as prefs get
  // overwritten with the new one — otherwise the old server keeps pushing to us.
  fun unregister(host: String, cookie: String, token: String) {
    post("$host/api/push/unregister", cookie, token)
  }

  private fun post(url: String, cookie: String, token: String) {
    Thread {
      try {
        val c = (URL(url).openConnection() as HttpURLConnection).apply {
          requestMethod = "POST"
          doOutput = true
          connectTimeout = 8000
          readTimeout = 8000
          setRequestProperty("Content-Type", "application/json")
          setRequestProperty("Cookie", cookie)
        }
        val body = "{\"token\":${jsonStr(token)},\"platform\":\"android\"}"
        c.outputStream.use { it.write(body.toByteArray()) }
        c.responseCode // fire the request; status is enough
        c.disconnect()
      } catch (e: Exception) {
      }
    }.start()
  }

  private fun jsonStr(s: String) =
    "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
KOTLIN
perl -pi -e "s/__PKG__/$PKG/" "$APP_PKG_DIR/PushReg.kt"

# --- Firebase Cloud Messaging (only when google-services.json is provided) ----
# Drop your Firebase Android config at platforms/android/google-services.json to
# enable push. Without it, none of the Firebase Gradle/manifest/code is applied,
# so the app builds and runs exactly as before — just without notifications.
GS="platforms/android/google-services.json"
SVC="$APP_PKG_DIR/ZenitharMessagingService.kt"
if [ -f "$GS" ]; then
  cp "$GS" "$GEN/app/google-services.json"

  # Root Gradle: the google-services plugin classpath.
  ROOT_GRADLE="$GEN/build.gradle.kts"
  grep -q 'google-services' "$ROOT_GRADLE" || perl -0pi -e 's{(classpath\("org\.jetbrains\.kotlin:kotlin-gradle-plugin[^\n]*\n)}{$1        classpath("com.google.gms:google-services:4.4.2")\n}' "$ROOT_GRADLE"

  # App Gradle: Firebase Messaging (via BoM) + apply the plugin.
  APP_GRADLE="$GEN/app/build.gradle.kts"
  grep -q 'firebase-bom' "$APP_GRADLE" || perl -0pi -e 's{(implementation\("androidx\.webkit:webkit[^\n]*\n)}{$1    implementation(platform("com.google.firebase:firebase-bom:33.7.0"))\n    implementation("com.google.firebase:firebase-messaging")\n}' "$APP_GRADLE"
  grep -q 'com.google.gms.google-services' "$APP_GRADLE" || printf '\napply(plugin = "com.google.gms.google-services")\n' >> "$APP_GRADLE"

  # Manifest: notification permission + the messaging service.
  grep -q 'POST_NOTIFICATIONS' "$MF" || perl -0pi -e 's{(<uses-permission android:name="android.permission.INTERNET"\s*/>)}{$1\n    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>}' "$MF"
  grep -q 'ZenitharMessagingService' "$MF" || perl -0pi -e "s{(\\s*</application>)}{\n        <service android:name=\"$PKG.ZenitharMessagingService\" android:exported=\"false\">\n            <intent-filter>\n                <action android:name=\"com.google.firebase.MESSAGING_EVENT\"/>\n            </intent-filter>\n        </service>\$1}" "$MF"

  # The service (Firebase-dependent — created only here). Persists the token and
  # registers it; backgrounded "notification" pushes are drawn by the system.
  cat > "$SVC" <<'KOTLIN'
package __PKG__

import com.google.firebase.messaging.FirebaseMessagingService
import com.google.firebase.messaging.RemoteMessage

class ZenitharMessagingService : FirebaseMessagingService() {
  override fun onNewToken(token: String) {
    getSharedPreferences("zenithar", MODE_PRIVATE).edit().putString("fcm_token", token).apply()
    PushReg.register(this)
  }

  override fun onMessageReceived(message: RemoteMessage) {
    // Foreground only — backgrounded notifications are shown by the system, and
    // the live web UI already surfaces the message. Nothing to do for now.
  }
}
KOTLIN
  perl -pi -e "s/__PKG__/$PKG/" "$SVC"
  echo "→ android: FCM wired (google-services.json present)"
else
  rm -f "$SVC"
  echo "→ android: FCM off (drop platforms/android/google-services.json to enable)"
fi
